### ISSUE TITLE
Old csslint version used

### ISSUE THREAD

**Issue by midsbie** [hyungjs/csslint-loader#9]
I have found that linting some CSS files containing SVG styling using csslint-loader is creating a number of problems in the form of errors emitted by csslint and there is no way of mitigating this other than to ignore rules (e.g. `known-properties`), which is hardly ideal.  This is because csslint-loader internally uses csslint 0.10.0, which I believe is a 2013 release, as opposed to a more recent version that handles SVG styling correctly. 

Is there a particular reason for sticking with such an old release, I wonder? Would it be possible to bump up the required csslint version, perhaps even matching csslint's stable releases as they come out? (currently it is 1.0.4!)

**Comment by hyungjs** [comment]
@miguel-guedes

Sorry I haven't really been keeping this up-to-date since I've been using sass for all my work. Having said that, I'll upgrade the csslint version when I'm back from vacation.

Can you please provide me with a sample css file with the SVG that is causing issues so I can confirm the csslint bump fixes the issue?

Thanks

**Comment by midsbie** [comment]
Not a problem, @hyungjs, and thanks for getting back to me.

Here's a code snippet that should induce the old csslint used by csslint-loader into producing errors:

```css
.path-area {
  fill: lightgrey;
  stroke-width: 0;
}

.path-line {
  fill: none;
  stroke: darkgrey;
  stroke-width: 1px;
}

.brush {
  stroke: grey;
  fill: black;
  fill-opacity: 0.2;
}

.axis .tick line {
  fill: none;
  stroke: black;
}

.axis .tick text {
  font: 10px sans-serif;
}

.histogram .x.axis .domain {
  fill: none;
  stroke: black;
}
```

As stated in the OP, newer versions of csslint do not produce SVG-related errors.

Thanks!
